export const SPATIAL_PDF_QUESTION_BANK = [
  {
    sequence: 1,
    pdfNumber: 1,
    pdfLabel: "1",
    liveQuestionId: 366,
    liveQuestionNumber: 76,
    assetFolder: "q076",
    text: "When put together, what 3-dimensional shape will you get?",
    correctOption: "B",
  },
  {
    sequence: 2,
    pdfNumber: 2,
    pdfLabel: "2",
    liveQuestionId: 367,
    liveQuestionNumber: 77,
    assetFolder: "q077",
    text: "When folded, what pattern is possible?",
    correctOption: "C",
  },
  {
    sequence: 3,
    pdfNumber: 3,
    pdfLabel: "3",
    liveQuestionId: 368,
    liveQuestionNumber: 78,
    assetFolder: "q078",
    text: "Which figure represents the assembly of the following pieces?",
    correctOption: "D",
  },
  {
    sequence: 4,
    pdfNumber: 4,
    pdfLabel: "4",
    liveQuestionId: 369,
    liveQuestionNumber: 79,
    assetFolder: "q079",
    text: "Which cube is obtained by folding the shape below?",
    correctOption: "D",
  },
  {
    sequence: 5,
    pdfNumber: 5,
    pdfLabel: "5",
    liveQuestionId: 370,
    liveQuestionNumber: 80,
    assetFolder: "q080",
    text: "Which cube is obtained by folding the shape below?",
    correctOption: "D",
  },
  {
    sequence: 6,
    pdfNumber: 6,
    pdfLabel: "6",
    liveQuestionId: 371,
    liveQuestionNumber: 81,
    assetFolder: "q081",
    text: "Which cube cannot be made based on the unfolded cube?",
    correctOption: "B",
  },
  {
    sequence: 7,
    pdfNumber: 7,
    pdfLabel: "7",
    liveQuestionId: 372,
    liveQuestionNumber: 82,
    assetFolder: "q082",
    text: "Which cube cannot be made based on the unfolded cube?",
    correctOption: "B",
  },
  {
    sequence: 8,
    pdfNumber: 8,
    pdfLabel: "8",
    liveQuestionId: 373,
    liveQuestionNumber: 83,
    assetFolder: "q083",
    text: "Which figure is a rotation of the object?",
    correctOption: "D",
  },
  {
    sequence: 9,
    pdfNumber: 9,
    pdfLabel: "9",
    liveQuestionId: 374,
    liveQuestionNumber: 84,
    assetFolder: "q084",
    text: "Which figure is a rotation of the object?",
    correctOption: "A",
  },
  {
    sequence: 10,
    pdfNumber: 10,
    pdfLabel: "10",
    liveQuestionId: 375,
    liveQuestionNumber: 85,
    assetFolder: "q085",
    text: "Which figure is a rotation of the given object?",
    correctOption: "C",
  },
  {
    sequence: 11,
    pdfNumber: 11,
    pdfLabel: "11",
    liveQuestionId: 376,
    liveQuestionNumber: 86,
    assetFolder: "q086",
    text: "Which figure is a top-down view of the given shape?",
    correctOption: "B",
  },
  {
    sequence: 12,
    pdfNumber: 12,
    pdfLabel: "12",
    liveQuestionId: 377,
    liveQuestionNumber: 87,
    assetFolder: "q087",
    text: "Which figure fits the given object, in order to make a cube?",
    correctOption: "A",
  },
  {
    sequence: 13,
    pdfNumber: 13,
    pdfLabel: "13",
    liveQuestionId: 378,
    liveQuestionNumber: 88,
    assetFolder: "q088",
    text:
      "Which figure fits the given object using rotation only, in order to make a square?",
    correctOption: "D",
  },
  {
    sequence: 14,
    pdfNumber: 14,
    pdfLabel: "14",
    liveQuestionId: 379,
    liveQuestionNumber: 89,
    assetFolder: "q089",
    text: "Which cube cannot be made based on the unfolded cube?",
    correctOption: "D",
  },
  {
    sequence: 15,
    pdfNumber: 15,
    pdfLabel: "15",
    liveQuestionId: 380,
    liveQuestionNumber: 90,
    assetFolder: "q090",
    text: "Which piece corresponds to the given solid?",
    correctOption: "C",
  },
  {
    sequence: 16,
    pdfNumber: 16,
    pdfLabel: "16",
    liveQuestionId: 381,
    liveQuestionNumber: 91,
    assetFolder: "q091",
    text: "Which figure is the rotation of object?",
    correctOption: "B",
  },
  {
    sequence: 17,
    pdfNumber: 17,
    pdfLabel: "17",
    liveQuestionId: 382,
    liveQuestionNumber: 92,
    assetFolder: "q092",
    text: "Which figure is the rotation of the object?",
    correctOption: "D",
  },
  {
    sequence: 18,
    pdfNumber: 18,
    pdfLabel: "18",
    liveQuestionId: 383,
    liveQuestionNumber: 93,
    assetFolder: "q093",
    text:
      "Which of the 4 figures presented (A, B, C, D) is a rotation of the first?",
    correctOption: "C",
  },
  {
    sequence: 19,
    pdfNumber: 19,
    pdfLabel: "19",
    liveQuestionId: 384,
    liveQuestionNumber: 94,
    assetFolder: "q094",
    text: "Which piece corresponds to the given solid?",
    correctOption: "C",
  },
  {
    sequence: 20,
    pdfNumber: 20,
    pdfLabel: "20",
    liveQuestionId: 385,
    liveQuestionNumber: 95,
    assetFolder: "q095",
    text: "Which piece corresponds to the given solid?",
    correctOption: "D",
  },
  {
    sequence: 21,
    pdfNumber: 21,
    pdfLabel: "21",
    liveQuestionId: 386,
    liveQuestionNumber: 96,
    assetFolder: "q096",
    text: "Which object can be made by folding the given shape?",
    correctOption: "C",
  },
  {
    sequence: 22,
    pdfNumber: 22,
    pdfLabel: "22",
    liveQuestionId: 387,
    liveQuestionNumber: 97,
    assetFolder: "q097",
    text: "Which figure can be formed using 2D rotation?",
    correctOption: "A",
  },
  {
    sequence: 23,
    pdfNumber: 22,
    pdfLabel: "22 (duplicate in source PDF)",
    liveQuestionId: 388,
    liveQuestionNumber: 98,
    assetFolder: "q098",
    text: "Which figure can be formed with the given pieces?",
    correctOption: "C",
  },
  {
    sequence: 24,
    pdfNumber: 23,
    pdfLabel: "23",
    liveQuestionId: 389,
    liveQuestionNumber: 99,
    assetFolder: "q099",
    text: "To which object does the given top view correspond?",
    correctOption: "A",
  },
  {
    sequence: 25,
    pdfNumber: 24,
    pdfLabel: "24",
    liveQuestionId: 390,
    liveQuestionNumber: 100,
    assetFolder: "q100",
    text: "Which figure is a vertical reflection across the x axis?",
    correctOption: "A",
  },
  {
    sequence: 26,
    pdfNumber: 25,
    pdfLabel: "25",
    liveQuestionId: null,
    liveQuestionNumber: null,
    assetFolder: "q101",
    text: "Which cube can be formed by folding the given shape?",
    correctOption: "D",
  },
  {
    sequence: 27,
    pdfNumber: 26,
    pdfLabel: "26",
    liveQuestionId: null,
    liveQuestionNumber: 102,
    assetFolder: "q102",
    text: "Which of these images is the top view of the given object?",
    correctOption: "B",
  },
];

export const LIVE_SPATIAL_RELATIONS_OVERRIDES = SPATIAL_PDF_QUESTION_BANK.filter(
  (question) => Number(question.liveQuestionId) >= 366 && Number(question.liveQuestionId) <= 390
).map(({ text, correctOption }) => ({
  text,
  correctOption,
}));
