// <picture> wrapper that serves the AVIF/WebP variants generated by
// scripts/optimizeImages.mjs, falling back to the original PNG/JPG.
//
// Usage:
//   <AssetImage name="jumpstart-logo" alt="Jumpstart"
//               width={333} height={235} className="h-11 w-auto" />
//
// `name` is the asset's basename without extension. The variants are
// resolved at build time by the glob below, so a missing variant is a
// build-time no-op rather than a 404 at runtime — if the optimizer has
// not run, the component silently degrades to the plain <img>.
//
// width/height are required. They are the *intrinsic* dimensions and
// exist to give the browser an aspect ratio to reserve space with; CSS
// (className) still controls the rendered size. Omitting them is what
// produces the classic "image pops in and shoves the page down" layout
// shift, so the prop is not optional.

import { useMemo } from "react";

// Eager URL glob: Vite rewrites each match to its final hashed asset
// path at build time and tree-shakes anything unreferenced.
const VARIANTS = import.meta.glob("../assets/*.{avif,webp}", {
  eager: true,
  query: "?url",
  import: "default",
});

const ORIGINALS = import.meta.glob("../assets/*.{png,jpg,jpeg}", {
  eager: true,
  query: "?url",
  import: "default",
});

// "../assets/jumpstart-logo-640.webp" -> { name, width, ext }
const parseKey = (key) => {
  const file = key.split("/").pop();
  const [, stem, ext] = file.match(/^(.*)\.(avif|webp|png|jpe?g)$/i) || [];
  if (!stem) return null;

  // A trailing -<digits> is a responsive width, not part of the name.
  const m = stem.match(/^(.*)-(\d+)$/);
  return m
    ? { name: m[1], width: Number(m[2]), ext: ext.toLowerCase() }
    : { name: stem, width: null, ext: ext.toLowerCase() };
};

// Built once per module load, not per render.
const INDEX = (() => {
  const index = new Map();

  const add = (key, url) => {
    const parsed = parseKey(key);
    if (!parsed) return;
    const entry = index.get(parsed.name) || { avif: [], webp: [], fallback: null };
    if (parsed.ext === "avif" || parsed.ext === "webp") {
      entry[parsed.ext].push({ url, width: parsed.width });
    } else if (!parsed.width) {
      entry.fallback = url;
    }
    index.set(parsed.name, entry);
  };

  for (const [k, v] of Object.entries(VARIANTS)) add(k, v);
  for (const [k, v] of Object.entries(ORIGINALS)) add(k, v);
  return index;
})();

// A variant with width:null is the natural-size one. It still belongs in
// the srcset, so it is emitted at the declared intrinsic width.
const toSrcSet = (list, intrinsicWidth) =>
  list
    .map(({ url, width }) => `${url} ${width ?? intrinsicWidth}w`)
    .sort((a, b) => parseInt(a.split(" ")[1], 10) - parseInt(b.split(" ")[1], 10))
    .join(", ");

export default function AssetImage({
  name,
  alt,
  width,
  height,
  sizes,
  className = "",
  // Above-the-fold images should pass priority so the browser fetches
  // them at high priority and does not defer them; everything else stays
  // lazy, which is the right default for the long tail of page images.
  priority = false,
  ...rest
}) {
  const entry = INDEX.get(name);

  const sources = useMemo(() => {
    if (!entry) return [];
    return [
      { type: "image/avif", srcSet: toSrcSet(entry.avif, width) },
      { type: "image/webp", srcSet: toSrcSet(entry.webp, width) },
    ].filter((s) => s.srcSet);
  }, [entry, width]);

  if (!entry?.fallback) {
    // Unknown asset — render nothing rather than a broken image. A
    // mistyped name shows up immediately in dev as a missing element.
    if (import.meta.env.DEV) {
      console.warn(`AssetImage: no asset found for name="${name}"`);
    }
    return null;
  }

  const img = (
    <img
      src={entry.fallback}
      alt={alt}
      width={width}
      height={height}
      sizes={sizes}
      className={className}
      loading={priority ? "eager" : "lazy"}
      // fetchPriority is the part that actually matters for LCP: without
      // it a high-priority image still queues behind the JS bundle.
      fetchPriority={priority ? "high" : "auto"}
      decoding={priority ? "sync" : "async"}
      {...rest}
    />
  );

  if (!sources.length) return img;

  return (
    <picture>
      {sources.map((s) => (
        <source key={s.type} type={s.type} srcSet={s.srcSet} sizes={sizes} />
      ))}
      {img}
    </picture>
  );
}
